name: Main workflow
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Prettier Format Check
        run: npm run format-check

      - name: ESLint Check
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Send Coverage
        continue-on-error: true
        timeout-minutes: 1
        run: curl -s https://codecov.io/bash | bash -s -- -t ${{secrets.CODECOV_TOKEN}} -f coverage/clover.xml -n github-actions-codecov-${{ matrix.operating-system }}-php${{ matrix.php-versions }}